// Auto-generated by https://github.com/react-spring/gltfjsx

import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Snapdragon(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, './ThreeJS/assets/snapdragon-gltf/snapdragon.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="OSG_Scene">
        <group name="RootNode_(gltf_orientation_matrix)" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="RootNode_(model_correction_matrix)">
            <group name="snapdragonobjcleanermaterialmergergles">
              <mesh material={materials['lambert2SG']} geometry={nodes[''].geometry} />
            </group>
          </group>
        </group>
      </scene>
    </group>
  )
}
