[build]
  publish = "public"
  command = "npm run build"
    functions = "functions"
[build.environment]
  NODE_VERSION = "16.10.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  GO_IMPORT_PATH = "github.com/justrmarks/shedaddy-com"
